// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxgzdjawzsfstdxaqunv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Z3pkamF3enNmc3RkeGFxdW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjA2NjksImV4cCI6MjA2Nzg5NjY2OX0.Oaf7k0tO04EJW-nACjj-WV4tXsCpMv43AGhgnkUhI7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});